Create ticket_count_per_status_by_paying_customer.md
panoplyio/sql-library pull request #18
Opened 2020-10-01 21:23 UTC by RegieAba

This query shows how many zendesk tickets per status a paying customer has. Paying customers are derived from Salesforce data and the ticket count is derived from the Zendesk data. User data from the two datasources are linked by email.

2020-10-02 22:18 UTC, alonbrody requested changes

2020-10-02 22:18 UTC, alonbrody commented on zendesk/queries/ticket_count_per_status_by_paying_customer.md
> +requirements: Collect the `Lead` and `Opportunity` objects with the Panoply Salesforce data source and also the `Users` and `Organizations` Resources form the Zendesk data source.
What about `tickets` data from Zendesk?

2020-10-02 22:18 UTC, alonbrody commented on zendesk/queries/ticket_count_per_status_by_paying_customer.md
> +    EXTRACT(quarter FROM zt."created_at") = EXTRACT(quarter FROM CURRENT_DATE)
`EXTRACT` only returns the quarter number (4 for example). Should use `date_trunc` which will produce the first day of the quarter

2020-10-02 22:18 UTC, alonbrody commented on zendesk/queries/ticket_count_per_status_by_paying_customer.md
> +`closed`| Zendesk tickets count under the "closed" status
Missing `total`

2020-10-02 23:37 UTC, RegieAba commented
Changed the directory from zendesk to zendesk-salesforce.

2020-10-05 20:55 UTC, alonbrody approved these changes

2020-10-06 20:17 UTC, merged