salesforce: revenue and loss grouped by opportunity type query
panoplyio/sql-library pull request #22
Opened 2020-10-01 22:29 UTC by RegieAba

This query sums the total amount from opportunities grouped by type. A total is displayed at the bottom

2020-10-02 04:01 UTC, trevorfox requested changes
Looks good. Please keep tabs consistent in `SELECT` and `WHERE` clauses and capitalize the final `ORDER BY`.

2020-10-02 17:38 UTC, RegieAba commented
> Looks good. Please keep tabs consistent in `SELECT` and `WHERE` clauses and capitalize the final `ORDER BY`.

Thank you for checking. I pushed some updates. Please review again. Thank you!

2020-10-02 22:50 UTC, alonbrody requested changes

2020-10-02 22:50 UTC, alonbrody commented on salesforce/queries/revenue_and_loss_by_opportunity_type.md
> +  EXTRACT(quarter FROM "closedate") = EXTRACT(quarter FROM CURRENT_DATE)
Use `date_trunc` instead of `extract`

2020-10-02 22:50 UTC, alonbrody commented on salesforce/queries/revenue_and_loss_by_opportunity_type.md
> +  count(*) AS "opps"
Should be all caps

2020-10-02 22:50 UTC, alonbrody commented on salesforce/queries/revenue_and_loss_by_opportunity_type.md
> +  count(*) AS "opps"
should be all caps

2020-10-05 20:57 UTC, alonbrody approved these changes

2020-10-05 20:57 UTC, alonbrody commented on salesforce/queries/revenue_and_loss_by_opportunity_type.md
> +  date_trunc('quarter', "closedate") = date_trunc('quarter', CURRENT_DATE)
`DATE_TRUNC` Should be all caps

2020-10-05 20:57 UTC, alonbrody commented on salesforce/queries/revenue_and_loss_by_opportunity_type.md
> +  date_trunc('quarter', "closedate") = date_trunc('quarter', CURRENT_DATE)
`DATE_TRUNC` Should be all caps

2020-10-06 20:13 UTC, RegieAba commented
@trevorfox done with the requests here.

2020-10-30 22:37 UTC, trevorfox requested changes
Hey @RegieAba everything looks great... except we've changed the formatting for these. Could you please update the formatting (remove H1, remove "Salesforce: " from the title, and update the table formatting) and then it's good to go!

2020-11-04 17:43 UTC, trevorfox approved these changes

2020-11-04 17:44 UTC, merged